---
title: "Initiate exotic project"
output: html_document
---

# Date stamp
```{r setup}
knitr::opts_chunk$set(echo = TRUE)

files.dstamp <- as.character(Sys.Date())
files.dstamp
```

# Define data for project
```{r}
tcc.cancers <- c("THO-LungCancer", "GI-ColorectalCancer", "SAR-Sarcoma",
                 # "THY-Thyroid_Batch1", "THY-Thyroid_Batch2",
                 "RenalCellCarcinoma", "GU-BladderCancer", "CUT-Melanoma")
tcga.cancers <- c("LUAD", "LUSC", "COAD", "READ", "SARC", 
                  # "THCA",
                  "SKCM", "KIRC", "BLCA")
```

# Load pipeline
```{r, message=FALSE, warning=FALSE}
abstracted.files <- list.files("/fs/ess/PAS1695/exoticpipe/R/")
lapply(abstracted.files, function(x) source(paste0("/fs/ess/PAS1695/exoticpipe/R/", x)))
```

# Run pipeline and check for failures
```{r}
make(
  plan.TCCandTCGA, # defined in R/plan.R
  verbose = 2
)

# loadd(tcga.meta)
# vis_drake_graph(plan, targets_only = T, file = paste0(files.dstainstamp, "_schema-of-plan.pdf"),
                # navigationButtons = F)
drake_ggraph(plan.TCCandTCGA, targets_only = T, main = "Exo[n] processing", label_nodes = T) 
  # ggplot2::ggsave(paste0(files.dstamp, "_schema-of-plan.pdf"), width = 25, height = 15)
```


```{r}
outdir <- file.path("/fs/ess/PAS1695/projects/exotic/data/drake-output/", files.dstamp)

for(i in plan.TCCandTCGA$target){
  tmp <- readd(i, character_only = T)
  saveRDS(tmp, paste0(outdir, "/", i, ".RDS"))
}

hist <- drake_history()
write.csv(hist, paste0(outdir, "/drake-history.csv"), row.names = F)
```