---
title: "figures_correlations"
author: "Rebecca Hoyd"
date: "February 6, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(tidyr)
library(broom)
```

# Load data
```{r, eval = F}
exo.ra <- read.csv("../../data/agg_exo-ra_taxonomy.csv", stringsAsFactors = F)
immunecells <- read.csv("../../data/split-deconvolved-aggcuff_absolute/2019-12-09_cibersort_absolute_aggregated+TILS.csv", stringsAsFactors = F) %>%
  select(cancer, everything()) %>%
  rename("sample" = "Input.Sample")

kingphyl <- read.csv("../../data/fix-king-assign_manual-edits.csv", stringsAsFactors = F)
```

```{r, eval = F}

exoRAtowideprev <- function(data, taxlev){
  tmp <- data
  tmp$Taxa <- tmp[[taxlev]]
  tmp.wide<- tmp %>%
    filter(!is.na(Taxa)) %>%
    mutate(Taxa = paste(taxlev, Taxa, sep = "_")) %>%
    group_by(sample, Taxa) %>%
    summarise(ra = sum(ra, na.rm = T)) %>%
    spread(key = "Taxa", value = "ra")
  
  tmp.wide[is.na(tmp.wide)] <- 0
  # tmp.prev <- bind_rows(lapply(tmp.wide[,-1], function(x) ifelse(x > 0, 1, 0))) %>%
  #   mutate(sample = tmp.wide$sample) %>%
  #   select(sample, everything())
  return(tmp.wide)
}
```

```{r, eval = F}
exo.taxfix.domain <- exo.ra %>%
  filter(is.na(taxonomy)) %>%
  mutate(domain = ifelse(grepl("phage|virus", spec.join, ignore.case = TRUE), "Viruses", domain),
         domain = ifelse(grepl("calothrix", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("anabaena", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("chondrocystis", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("cyanobacterium", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("dolichospermum", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("euhalothece", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("fischerella", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("geitlerinema", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("geminocystis", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("gloeobacter", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("gloeothece", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("limnospira", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("microcoleus", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("moorea", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("nostoc", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("oscillatoria", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("prochlorococcus", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("rivularia", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("synechococcus", spec.join, ignore.case = TRUE) & !grepl("phage|virus", spec.join,
                                                                                        ignore.case = TRUE),
                         "Bacteria", domain),
         domain = ifelse(grepl("tenericutes", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("trichodesmium", spec.join, ignore.case = TRUE), "Bacteria", domain)
         )

exo.ra <-exo.ra %>%
  filter(!is.na(taxonomy)) %>%
  select(-kingdom) %>%
  left_join(kingphyl)

exo.ra <- bind_rows(exo.ra, exo.taxfix.domain)




taxalevels <- c("domain", "kingdom", "phylum", "class", "order", "family", "genus", "species")

exo.wide.list <- lapply(taxalevels, function(x) exoRAtowideprev(exo.ra, x))
names(exo.wide.list) <- taxalevels

microbes <- unlist(lapply(exo.wide.list, function(x) colnames(x)[-1]))

exo <- bind_cols(exo.wide.list) %>%
  column_to_rownames(var = "sample") %>%
  select(-contains("sample")) %>%
  rownames_to_column(var = "sample") %>%
  select(sample, everything())

exo[is.na(exo)] <- 0
```



```{r}
oldlabs <- c("B.cells.naive", "B.cells.memory", 
             "Plasma.cells", "T.cells.CD8", "T.cells.CD4.naive", 
             "T.cells.CD4.memory.resting", "T.cells.CD4.memory.activated", "T.cells.follicular.helper",
             "T.cells.gamma.delta", "T.cells.regulatory..Tregs.", "NK.cells.resting", 
             "NK.cells.activated", "Monocytes", "Macrophages.M0", 
             "Macrophages.M1", "Macrophages.M2", "Dendritic.cells.resting", 
             "Dendritic.cells.activated", "Mast.cells.resting", "Mast.cells.activated", 
             "Eosinophils", "Neutrophils", "TILs")

newlabs <- c("Naive B Cells", "Memory B Cells", 
             "Plasma Cells", "CD8 T Cells", "Naive CD4 T Cells", 
             "Resting Memory CD4 T Cells", "Activated Memory CD4 T Cells", "Follicular Helper T Cells",
             "Gamma Delta T Cells", "Regulatory T Cells", "Resting NK Cells", 
             "Activated NK Cells", "Monocytes", "M0 Macrophages",
             "M1 Macrophages", "M2 Macrophages", "Resting Dendritic Cells", 
             "Activated Dendritic Cells", "Resting Mast Cells", "Activated Mast Cells", 
             "Eosonophils", "Neutrophils", "TILs")


```

# Test correlations
```{r, eval = F}
microbes <- colnames(exo)[-1]
imcells <- colnames(immunecells)[-c(1:3)]
cancers <- unique(immunecells$cancer)

micim <- exo %>%
  left_join(immunecells)
```

```{r}
# cor.can <- list()
# for(c in cancers){
#   micim.tmp <- micim %>%
#     filter(cancer == c)
# 
#   cor.can[[c]] <- lapply(microbes, function(m) lapply(imcells, function(i) cor.test(micim.tmp[[m]], micim.tmp[[i]],
#                                                                     method = "spearman") %>%
#                                         tidy() %>%
#                                         mutate(im.cell = i, microbe = m, cancer = c)))
# 
# 
# }
# 
# test <- lapply(cor.can, function(x) lapply(x, function (y) bind_rows(y)))
# test <- lapply(test, function(x) bind_rows(x))
# cor.can <- bind_rows(test)
# 
# write.csv(cor.can, "../../data/AACR_correlations.csv", row.names = F)

cor.can <- read.csv("../../data/AACR_correlations.csv")
```

# Build heatmaps

```{r triangle map}
cor.dat <- cor.can %>%
  select("estimate", "p.value", "microbe", "im.cell", "cancer") %>%
  # group_by(cancer) %>%
  # mutate(padj = p.adjust(p.value, method = "fdr")) %>%
  # ungroup() %>%
  separate(taxa, by = "_", into = c("Taxa.Level", "microbe"), extra = "merge") %>%
  filter(Taxa.Level == "genus" & !is.na(estimate))
# cor.dat <- cor.dat[!duplicated(cor.dat),]

cor.dat %>%
  filter(cancer %in% c("CUT", "GU", "RCC")) %>%
  mutate(estimate = ifelse(p.value < 0.05, estimate, -2)) %>%
  ggplot(aes(x = microbe, y = im.cell, fill = estimate)) +
  facet_wrap(vars(cancer)) +
  geom_tile() +
  # geom_text(aes(label = ifelse(p.value < 0.05, "s", ""))) +
  scale_fill_distiller(guide = "legend", breaks = seq(-1,1,.2), 
                       limits = c(-1, 1), values = seq(0,1,.1),
                       type = "div", palette = "RdBu", direction = -1,
                       name = "Correlation",
                       na.value = "white") +
  labs(x = "", y = "") +
  scale_x_discrete(position = "top") +
  scale_y_discrete(breaks = oldlabs, labels = newlabs) +
  theme_bw() +
  theme(axis.text.x = element_blank()) +
  ggsave("../../figures/AACR/correlation-heatmap_toprow.pdf", width = 8, height = 3.5)

cor.dat %>%
  filter(!cancer %in% c("CUT", "GU", "RCC")) %>%
  mutate(estimate = ifelse(p.value < 0.05, estimate, -2)) %>%
  ggplot(aes(x = microbe, y = im.cell, fill = estimate)) +
  facet_wrap(vars(cancer)) +
  geom_tile() +
  # geom_text(aes(label = ifelse(p.value < 0.05, "s", ""))) +
  scale_fill_distiller(guide = "legend", breaks = seq(-.5,.5,.1), 
                       limits = c(-.5, .5), values = seq(0,1,.1),
                       type = "div", palette = "RdBu", direction = -1,
                       name = "Correlation",
                       na.value = "white") +
  labs(x = "", y = "") +
  scale_x_discrete(position = "top") +
  scale_y_discrete(breaks = oldlabs, labels = newlabs) +
  theme_bw() +
  theme(axis.text.x = element_blank()) +
  ggsave("../../figures/AACR/correlation-heatmap_bottomrow.pdf", width = 8, height = 3.5)
```