---
title: "Summary figures"
author: "Rebecca Hoyd"
date: "February 6, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(forcats)
library(ggdendro)
library(RColorBrewer)
```

# Load data

```{r}
exo.ra <- read.csv("../../data/agg_exo-ra_taxonomy.csv", header = TRUE, stringsAsFactors = F)
immunecells <- read.csv("../../data/split-deconvolved-aggcuff_absolute/2019-12-09_cibersort_absolute_aggregated+TILS.csv")
```

```{r}
oldlabs <- c("B.cells.naive", "B.cells.memory", 
             "Plasma.cells", "T.cells.CD8", "T.cells.CD4.naive", 
             "T.cells.CD4.memory.resting", "T.cells.CD4.memory.activated", "T.cells.follicular.helper",
             "T.cells.gamma.delta", "T.cells.regulatory..Tregs.", "NK.cells.resting", 
             "NK.cells.activated", "Monocytes", "Macrophages.M0", 
             "Macrophages.M1", "Macrophages.M2", "Dendritic.cells.resting", 
             "Dendritic.cells.activated", "Mast.cells.resting", "Mast.cells.activated", 
             "Eosinophils", "Neutrophils", "TILs")

newlabs <- c("Naive B Cells", "Memory B Cells", 
             "Plasma Cells", "CD8 T Cells", "Naive CD4 T Cells", 
             "Resting Memory CD4 T Cells", "Activated Memory CD4 T Cells", "Follicular Helper T Cells",
             "Gamma Delta T Cells", "Regulatory T Cells", "Resting NK Cells", 
             "Activated NK Cells", "Monocytes", "M0 Macrophages",
             "M1 Macrophages", "M2 Macrophages", "Resting Dendritic Cells", 
             "Activated Dendritic Cells", "Resting Mast Cells", "Activated Mast Cells", 
             "Eosonophils", "Neutrophils", "TILs")

labsjoin <- as.data.frame(cbind(celltype = oldlabs, newlabs), stringsAsFactors = F)
```

# Microbe stacked bar

```{r format exo.ra for the figures}

exo.ra.phyl <- exo.ra %>%
  group_by(sample, phylum) %>%
  summarise(ra = sum(ra, na.rm = T)) %>%
  as.data.frame()

choosephyl <- exo.ra.phyl %>%
  group_by(phylum) %>%
  summarise(med.abun = median(ra)) %>%
  arrange(desc(med.abun)) %>%
  filter(med.abun > 0 & !is.na(phylum))

exo.ra.phyl %>%
  ggplot(aes(x = ra)) +
  facet_wrap(vars(phylum)) +
  geom_histogram() +
  ggsave("../../figures/AACR/investigate-phylum-distributions.png")


exo.ra.phyl.fil <- exo.ra.phyl %>%
  filter(phylum %in% choosephyl$phylum)

```

```{r get clustering}
exo.ra.phyl.w <- exo.ra.phyl.fil %>%
  spread(key = "phylum", value = "ra") %>%
  column_to_rownames(var = "sample")

exo.dend <- exo.ra.phyl.w %>%
  dist() %>%
  hclust() %>%
  as.dendrogram() %>%
  dendro_data()

canc.key <- immunecells[, c("Input.Sample", "cancer")] %>%
  rename("label" = "Input.Sample")

exo.dend$labels <- exo.dend$labels %>%
  left_join(canc.key)

sampord <- exo.dend$labels$label
```

```{r}
ggplot(exo.dend$segments) +
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_point(data = exo.dend$labels, aes(x, y, color = cancer), shape = "square") +
  scale_color_brewer(palette = "Dark2", name = "Cancer") +
  theme_void() +
  ggsave("../../figures/AACR/clustering_samples-by-cancer.emf", width = 10, height = 4)

```

```{r}
getPalette <- colorRampPalette(brewer.pal(8, "Set1"))
ncolor <- length(unique(exo.ra.phyl.fil$phylum))

exo.ra.phyl.fil %>%
  ggplot(aes(x = fct_relevel(sample, sampord),
             y = ra, 
             fill = phylum
             ))+
  geom_bar(position="fill", stat = "identity") +
  labs(x = "", y = "") +
  scale_fill_manual(breaks = unique(exo.ra.phyl.fil$phylum), values = getPalette(ncolor), name = "Phylum") +
  theme_minimal() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), panel.grid.major = element_blank()) +
  ggsave("../../figures/AACR/stacked-bar_microbes.emf", height = 10, width = 10)

```

# Immune cell figures

## stacked bar

```{r}
immunecells.l <- immunecells %>%
  select(-X) %>%
  gather(-Input.Sample, -cancer, key = "celltype", value = "percent")

get.cell.ord <- immunecells.l %>%
  group_by(celltype) %>%
  summarise(mean.pr = mean(percent)) %>%
  arrange(mean.pr)

immunecells.l %>%
  filter(celltype != "TILs") %>%
  ggplot(aes(x = Input.Sample,
             y = percent,
             # fill = fct_relevel(celltype, get.cell.ord$celltype)
             fill = celltype
             ))+
  facet_wrap(vars(cancer), scales = "free_x", nrow = 1) +
  geom_bar(position="fill", stat = "identity") +
  labs(x = "", y = "") +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.x = element_blank(), axis.ticks.x = element_blank(), 
        panel.grid.major = element_blank()) +
  ggsave("../../figures/AACR/stacked-bar_immune-cells.emf", height = 10, width = 10)
```

## Boxplots by cancer

```{r}
immunecells.l %>%
  ggplot(aes(x = cancer, y = percent)) +
  geom_boxplot() +
  facet_wrap(vars(celltype), scales = "free_y", ncol = 3) +
  labs(x = "", y = "") +
  # scale_x_discrete(breaks = oldlabs, labels = newlabs) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggsave("../../figures/AACR/boxplot_immune-by-cancer.emf", height = 15)
```

## Boxplots of just CD8+ Tcells and TILs by cancer
```{r}
immunecells.l %>%
  filter(celltype %in% c("T.cells.CD8", "TILs", "Macrophages.M1", "Macrophages.M2",
                         "NK.cells.activated", "NK.cells.resting", "T.cells.CD4.memory.resting")) %>%
  left_join(labsjoin) %>%
  ggplot(aes(x = cancer, y = percent, fill = cancer)) +
  geom_boxplot(show.legend = F) +
  facet_wrap(vars(newlabs), scales = "free_y", nrow = 2) +
  labs(x = "", y = "") +
  scale_fill_brewer(name = "Cancer", palette = "Dark2") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggsave("../../figures/AACR/boxplot_cd8-and-TILs.emf", width = 10)
```
