---
title: "Make Table 1: Cohort characteristics"
author: "Rebecca Hoyd"
date: "February 6, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tableone)
library(forcats)
library(glue)
library(readxl)
```

# Load data
```{r}
# I'm storing these in my T drive as I suspect the may have identifiable information
clinfiles <- list.files("T:/Labs/Spakowicz/data/exoTCC/", full.names = F)
clinfiles <- paste0("T:/Labs/Spakowicz/data/exoTCC/", clinfiles)

clindat <- lapply(clinfiles, function(x) read_excel(x))
```


# Coercing the clinical data into a tidier object
```{r}

for(i in 1:length(clindat)){
  # First, I don't want to have to deal with names poorly formatted for R. 
  colnames(clindat[[i]]) <- make.names(colnames(clindat[[i]]))
}

# Now, let's display the new column names and find the information needed for the table

lapply(clindat, function(x) colnames(x))
```
While the first two objects have similar naming schemes and information available, the second object may need to be handled separately.

```{r}
clindat.form1 <- bind_rows(clindat[[1]], clindat[[3]]) %>%
  mutate(Days.from.RT.Start.to.Last.Follow.Up.or.Death = as.numeric(Days.from.RT.Start.to.Last.Follow.Up.or.Death),
         Days.from.Hormone.Start.to.Last.Follow.Up.or.Death = as.numeric(Days.from.Hormone.Start.to.Last.Follow.Up.or.Death))

clindat.form2 <- clindat[[2]] %>%
  rename( "Cancer.Stage.at.Collection" = "Cancer.Stage.at.Collection..Best.CS.AJCC.") %>%
  select(colnames(clindat.form1))

clindat.form <- bind_rows(clindat.form1, clindat.form2)

```

```{r, eval=F}
write.csv(clindat.form, "T:/Labs/Spakowicz/data/exoTCC/clinical_aggregated.csv", row.names = F)
```

# Format  for the table

```{r learn about condensing variables}
clindat.form %>%
  mutate(Chemo.Drug.Name = tolower(Chemo.Drug.Name)) %>%
  separate(Chemo.Drug.Name, into = c('testChem')) %>%
  group_by(testChem) %>%
  tally() %>%
  arrange(desc(n))

clindat.form %>%
  mutate(I.O.Drug.Name = tolower(I.O.Drug.Name)) %>%
  separate(I.O.Drug.Name, into = c('testIO')) %>%
  group_by(testIO) %>%
  tally() %>%
  arrange(desc(n))
```

```{r}

# Select and adjust dataframe for Table 1
clindat.tabnames <- clindat.form %>%
  mutate(Stage  = Cancer.Stage.at.Collection,
         BMI = BMI.at.Collection,
         Age = Age.at.Collection,
         Sex = Gender,
         `Vital Status` = Vital.Status,
         IO = ifelse(I.O.Drug.Name == "N/A", "None", 
                     ifelse(grepl("pembro", I.O.Drug.Name, ignore.case = T), "Pembrolizumab", 
                            ifelse(grepl("nivo", I.O.Drug.Name, ignore.case = T), "Nivolumab",
                                   ifelse(grepl("beva", I.O.Drug.Name, ignore.case = T), "Bevacizumab",
                                          ifelse(grepl("folfiri", I.O.Drug.Name, ignore.case = T), "Folfiri",
                                                 ifelse(grepl("ipili", I.O.Drug.Name, ignore.case = T),
                                                        "Ipilimumab",ifelse(grepl("unknown", Chemo.Drug.Name,
                                                                                  ignore.case = T), 
                                                                            "Unknown", "Other"))))))),
         Chemotherapy = ifelse(Chemo.Drug.Name == "N/A", "none",
                               ifelse(grepl("cisp", Chemo.Drug.Name, ignore.case = T), "Cisplatin",
                                      ifelse(grepl("carb", Chemo.Drug.Name, ignore.case = T), "Carboplatin",
                                             ifelse(grepl("folfox", Chemo.Drug.Name, ignore.case = T), "Folfox",
                                                    ifelse(grepl("doxo", Chemo.Drug.Name, ignore.case = T),
                                                           "Doxorubicin",
                                                           ifelse(grepl("adria", Chemo.Drug.Name, ignore.case = T),
                                                                  "Adriamycin", 
                                                                  ifelse(grepl("unknown", Chemo.Drug.Name,
                                                                               ignore.case = T), "Unknown",
                                                                         "Other"))))))
         ),
         Radiation = ifelse(Radiation == "None", "No", "Yes"),
         Surgery = ifelse(grepl("None", Surgery), "No", "Yes"),
         Hormones = ifelse(is.na(Hormone.Therapy), "No", "Yes")
  )
```

# Creating table 1

```{r}
listVars <- c("BMI", "Age", "Sex", "Cancer", "Stage", "Vital Status", "IO", "Chemotherapy",
              "Radiation", "Surgery", "Hormones")
catVars <- c("Sex", "Cancer", "Stage", "Vital Status", "IO", "Chemotherapy", "Radiation", "Surgery", "Hormones")
```

```{r table 1}
table1 <- CreateTableOne(vars = listVars,
                         data = clindat.tabnames,
                         factorVars = catVars)
table1
```

```{r}
tabMat <- print(table1, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)
## Save to a CSV file
write.csv(tabMat, file = "../../figures/table1.csv")
```

