---
title: "analyses overlap"
author: "Rebecca Hoyd"
date: "6/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
# Functions

```{r}
getSurv <- function(){
  tcc.all <- readRDS("../data/survival_tcc_all-cancers.RDS") %>%
    bind_rows()
  tcga.all <- readRDS("../data/survival_tcga_all-cancers.RDS") %>%
    bind_rows()
  tcc.split <- readRDS("../data/survival_tcc_split-cancers.RDS")
  tcga.split <- readRDS("../data/survival_tcga_split-cancers.RDS")
  tcc.all.join <- tcc.all %>%
    mutate(cancer = "All")
  tcga.all.join <- tcga.all %>%
    mutate(cancer = "All")
  
  surv.res <- bind_rows(tcc.all.join, tcga.all.join, tcc.split, tcga.split)
  
  return(surv.res)
}

getClinCorr <- function(){
  tcc.all <- read.csv("../data/correlations_mic-clin_TCC.csv",
                      stringsAsFactors = F)
  tcc.split <- read.csv("../data/correlations_mic-clin_TCC_split-cancer.csv",
                        stringsAsFactors = F)
  tcga.all <- read.csv("../data/correlations_mic-clin_TCGA.csv",
                       stringsAsFactors = F)
  tcga.split <- read.csv("../data/correlations_mic-clin_TCGA_split-cancer.csv",
                         stringsAsFactors = F)
  
  tcc.res <- tcc.all %>%
    mutate(cancer = "All") %>%
    bind_rows(tcc.split)
  
  tcga.res <- tcga.all %>%
    mutate(cancer = "All") %>%
    bind_rows(tcga.split)
  
  tcc.newlab <- tcc.res %>%
    filter(p.value < 0.05) %>%
    mutate(TCC.est = estimate, 
           dir = TCC.est >= 0) %>%
    select(TCC.est, dir, microbe, score, cancer)
  
  tcga.newlab <- tcga.res %>%
    filter(p.value < 0.05) %>%
    mutate(TCGA.est = estimate, 
           dir = TCGA.est >= 0) %>%
    select(TCGA.est, dir, microbe, score, cancer)
  
  corrs.matched.1 <- inner_join(tcc.newlab, tcga.newlab)
  
  corrs.matched <- tcc.newlab %>%
    filter(cancer %in% c("LUAD", "LUSC", "SARC", "KIRC", "BLCA") & score == "bmi") %>%
    bind_rows(corrs.matched.1)
  return(corrs.matched)
}

getImCorr <- function(){
  tcc.all <- read.csv("/fs/ess/PAS1695/projects/exotic/data/correlations_mic-immune_TCC.csv",
                      stringsAsFactors = F)
  tcc.split <- read.csv("/fs/ess/PAS1695/projects/exotic/data/correlations_mic-immune_TCC_split-cancer.csv",
                        stringsAsFactors = F)
  tcga.all <- read.csv("/fs/ess/PAS1695/projects/exotic/data/correlations_mic-immune_TCGA.csv",
                       stringsAsFactors = F)
  tcga.split <- read.csv("/fs/ess/PAS1695/projects/exotic/data/correlations_mic-immune_TCGA_split-cancer.csv",
                         stringsAsFactors = F)
  
  tcc.res <- tcc.all %>%
    mutate(cancer = "All") %>%
    bind_rows(tcc.split)
  
  tcga.res <- tcga.all %>%
    mutate(cancer = "All") %>%
    bind_rows(tcga.split)
  
  corr.res <- bind_rows(tcc.res, tcga.res)
  return(corr.res)
}

```

# Load results

```{r}
surv <- getSurv()
clincorr <- getClinCorr()
imcorr <- getImCorr()
network.degree <- read.csv("../tables/network_microbe-hubbiness.csv",
                           stringsAsFactors = F)
network.between <- read.csv("../tables/network_betweenness-centrality.csv",
                            stringsAsFactors = F)
```

# Format

```{r get microbes from survival and immune cells}
surv.agree <- surv %>%
  mutate(hazard.dir = ifelse(hazard.ratio > 1, "neg", "pos"),
         signif = p.value < 0.05,
         dirsig = paste(hazard.dir, signif)) %>%
  select(microbe, dirsig, cancer, datset) %>%
  spread(key = "datset", value = "dirsig") %>%
  separate(TCC, into = c("TCC.dir", "TCC.sig")) %>%
  separate(TCGA, into = c("TCGA.dir", "TCGA.sig")) %>%
  mutate(agree.code = TCC.sig == T & TCGA.sig == T & TCC.dir == TCGA.dir) %>%
  filter(agree.code == T)

imcorr.sum <-imcorr %>%
  mutate(sig = ifelse(p.value < 0.05, "Yes", "No"),
         dir = ifelse(estimate < 0, "Negative", "Positive"),
         sigdir = paste(sig, dir),
         datset = ifelse(datset == "TCGA", "TCGA", "ORIEN")) %>%
  select(microbe, ImmuneCell, cancer, datset, sigdir) %>%
  pivot_wider(names_from = datset, values_from = sigdir) %>%
  separate(ORIEN, into = c("ORIEN.sig", "ORIEN.dir")) %>%
  separate(TCGA, into = c("TCGA.sig", "TCGA.dir"))

imcorr.match <- imcorr.sum %>%
  mutate(dirmatch = TCGA.dir == ORIEN.dir,
         heatcode = case_when(dirmatch == T & ORIEN.sig == "Yes" & 
                                TCGA.sig == "Yes" ~ "Match",
                              dirmatch == F & ORIEN.sig == "Yes" & 
                                TCGA.sig == "Yes" ~ "Disagree",
                              xor(ORIEN.sig  == "Yes", TCGA.sig == "Yes") ~
                                "One significant")) %>%
  filter(heatcode == "Match")
```

```{r format clinical correlations}
clincorr.form <- clincorr %>%
  filter(score != "MitoScore") %>%
  select(microbe, score) %>%
  mutate(signif = 1) %>%
  distinct() %>%
  pivot_wider(names_from = score, values_from = signif) %>%
  pivot_longer(cols = c('age','bmi','buffa.score','age'), 
               names_to = "score", values_to = "signif") %>%
  mutate(signif = ifelse(is.na(signif), 0,1)) %>%
  pivot_wider(names_from = score, values_from = signif) %>%
  rename("Correlation.Age" = "age",
         "Correlation.BMI" = "bmi",
         "Correlation.Hypoxia" = "buffa.score")


```

```{r rename network table columns}
network.between.form <- network.between %>%
  rename(microbe = node,
         Between.Centrality = betweencent)
network.degree.form <- network.degree %>%
  rename(Degree.Centrality = rank) %>%
  select(microbe, Degree.Centrality)
```

```{r}
results.df <- data.frame(microbe = unique(surv$microbe)) %>%
  left_join(clincorr.form) %>%
  mutate(Survival = ifelse(microbe %in% surv.agree$microbe, 1, 0),
         Correlation.Immune = ifelse(microbe %in% imcorr.match$microbe, 1, 0)) %>%
  pivot_longer(-microbe, names_to = "score", values_to = "signif") %>%
  mutate(signif = replace_na(signif, 0)) %>%
  pivot_wider(names_from = score, values_from = signif) %>%
  mutate(Times.Signif = Correlation.Immune + Survival +
           Correlation.Age + Correlation.BMI + Correlation.Hypoxia) %>%
  left_join(network.degree.form) %>%
  left_join(network.between.form) %>%
  arrange(desc(Times.Signif))
```

# Save

```{r}
write.csv(results.df, "../tables/summary_sig-accross-analyses.csv",
          row.names = F)
```

