---
title: "PCAs for batch effects"
author: "Rebecca Hoyd"
date: "2/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

# Load data

```{r}
drakedir <- "/fs/ess/PAS1695/projects/exotic/data/drake-output/2022-03-08/"

# tcc.batchres <- readRDS(file.path(drakedir, "tcc.batchres.RDS"))
# tcga.batchres <- readRDS(file.path(drakedir, "tcga.batchres.RDS"))

tcc.counts <- readRDS(file.path(drakedir, "tcc.counts.RDS"))
tcga.counts <- readRDS(file.path(drakedir, "tcga.counts.RDS"))

tcc.norm <- readRDS(file.path(drakedir, "tcc.exora.RDS"))
tcga.norm <-readRDS(file.path(drakedir, "tcga.exora.RDS"))

tcga.meta <- readRDS(file.path(drakedir, "tcga.meta.RDS"))
tcc.meta <- readRDS(file.path(drakedir, "tcc.meta.linkage.RDS"))
```

# PCAs

## Format

```{r}
counts.lowvar <- unlist(lapply(tcga.counts[,-1], function(x) var(x)))
summary(counts.lowvar)
counts.higvar <- names(subset(counts.lowvar, counts.lowvar > 0))


```

```{r}
tcga.counts.pc <- tcga.counts %>%
  select(c("sample", counts.higvar)) %>%
  column_to_rownames(var = "sample") 

counts.res  <- prcomp(tcga.counts.pc, scale. = T)$x %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  select(sample, PC1, PC2) %>%
  mutate(datset = "counts")

tcga.norm.pc <- tcga.norm %>%
  column_to_rownames(var = "sample") 
  # select(-Vibrio.phage.ValB1MD.2, -Staphylococcus.virus.Andhra)

norm.res  <- prcomp(tcga.norm.pc, scale. = T)$x%>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  select(sample, PC1, PC2) %>%
  mutate(datset = "normalized")
```

```{r}
norm.prc <- prcomp(tcga.norm.pc, scale. = T)
autoplot(norm.prc, loadings = T, loadings.label = T)
ggsave("../figures/pca_norm-loadings.png", width = 15)
```

## Plot

```{r}
pcs.res <- bind_rows(counts.res, norm.res) %>%
  left_join(tcga.meta)

pcs.res %>%
  ggplot(aes(x = PC1, y = PC2, color = ffpe.status, fill = ffpe.status)) +
  facet_wrap(vars(datset), scales = "free") +
  geom_point(alpha = .4) +
  stat_ellipse(geom = "polygon", alpha = .2) +
  scale_fill_viridis_d(aesthetics = c("color", "fill")) +
  theme_bw()
ggsave("../figures/pca_compare-FFPE.png")
```

## Repeat for TCC

## Format

```{r}
counts.lowvar <- unlist(lapply(tcc.counts[,-1], function(x) var(x)))
summary(counts.lowvar)
counts.higvar <- names(subset(counts.lowvar, counts.lowvar > 0))


```

```{r}
tcc.counts.pc <- tcc.counts %>%
  select(c("sample", counts.higvar)) %>%
  column_to_rownames(var = "sample") 

counts.res.tcc  <- prcomp(tcc.counts.pc, scale. = T)$x %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  select(sample, PC1, PC2) %>%
  mutate(datset = "counts")

tcc.norm.pc <- tcc.norm %>%
  column_to_rownames(var = "sample")

norm.res.tcc  <- prcomp(tcc.norm.pc, scale. = T)$x%>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  select(sample, PC1, PC2) %>%
  mutate(datset = "normalized")
```

```{r}
pcs.res.tcc <- bind_rows(counts.res.tcc, norm.res.tcc) %>%
  mutate(LibraryID = sample) %>%
  left_join(tcc.meta) %>%
  mutate(ffpe.status = `Tissue Preservation Method`)

pcs.res.tcc %>%
  ggplot(aes(x = PC1, y = PC2, color = ffpe.status, fill = ffpe.status)) +
  facet_wrap(vars(datset), scales = "free") +
  geom_point(alpha = .4) +
  stat_ellipse(geom = "polygon", alpha = .2) +
  scale_fill_viridis_d(aesthetics = c("color", "fill")) +
  theme_bw()
ggsave("../figures/pca_compare-FFPE_tcc.png")
```

## Repeat for combined

```{r}
all.counts <- bind_rows(tcc.counts.pc, tcga.counts.pc)
all.counts[is.na(all.counts)] <- 0
all.norm <- bind_rows(tcc.norm.pc, tcga.norm.pc)

counts.res.all  <- prcomp(all.counts, scale. = T)$x %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  select(sample, PC1, PC2) %>%
  mutate(datset = "counts")

norm.res.all  <- prcomp(all.norm, scale. = T)$x%>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  select(sample, PC1, PC2) %>%
  mutate(datset = "normalized")
```

```{r}
all.meta <- tcc.meta %>%
  mutate(sample = LibraryID,
         ffpe.status = ifelse(`Tissue Preservation Method` == "Frozen",
                              FALSE, TRUE)) %>%
  select(sample, ffpe.status) %>%
  bind_rows(tcga.meta)
pcs.res.all <- bind_rows(counts.res.all, norm.res.all) %>%
  left_join(all.meta)  %>%
  mutate(SequencingCenter = ifelse(is.na(SequencingCenter), "TCC", SequencingCenter))

pcs.res.all %>%
  ggplot(aes(x = PC1, y = PC2, color = SequencingCenter, fill = SequencingCenter)) +
  facet_wrap(vars(datset), scales = "free") +
  geom_point(alpha = .4) +
  stat_ellipse(geom = "polygon", alpha = .2) +
  scale_fill_viridis_d(aesthetics = c("color", "fill")) +
  theme_bw()
ggsave("../figures/pca_compare-FFPE_all.png")
```

# What are those groups?

```{r}
pcs.grouplab <- pcs.res.all %>%
  filter(datset == "normalized") %>%
  mutate(pc.group = ifelse(PC1 < -150, "ClusterA",
                           ifelse(PC1 < -50, "ClusterB",
                                  ifelse(PC2 > 200, "Outlier",
                                         "main.group"))))

pcs.grouplab %>% 
  group_by(pc.group) %>%
  tally()
```

```{r}
pcs.res %>%
  ggplot(aes(x = PC1, y = PC2, color = tissue_source_site, fill = tissue_source_site)) +
  facet_wrap(vars(datset), scales = "free") +
  geom_point(alpha = .4, show.legend = F) +
  stat_ellipse(geom = "polygon", alpha = .2, show.legend = F) +
  scale_fill_viridis_d(aesthetics = c("color", "fill")) +
  theme_bw()
```

# Volcano

```{r}

```


