---
title: "PCAs for batch effects"
author: "Rebecca Hoyd"
date: "2/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

# Load data

```{r}
drakedir.old <- "/fs/ess/PAS1695/projects/exotic/data/drake-output/2022-02-16/"
drakedir.new <- "/fs/ess/PAS1695/projects/exotic/data/drake-output/2022-03-08/"

norm.inputs.old <- readRDS(file.path(drakedir.old, "normalization.inputs.expr.RDS"))
norm.result.old <- readRDS(file.path(drakedir.old, "normalized.expr.RDS"))

norm.inputs.new <- readRDS(file.path(drakedir.new, "normalization.inputs.expr.RDS"))
norm.result.new <- readRDS(file.path(drakedir.new, "normalized.expr.RDS"))

# tcga.meta <- readRDS(file.path(drakedir, "tcga.meta.RDS"))
# tcc.meta <- readRDS(file.path(drakedir, "tcc.meta.linkage.RDS"))
```

# PCAs

## Original normalization formula

```{r}
old.counts <- norm.inputs.old[[1]] %>%
  as.data.frame()
counts.lowvar <- unlist(lapply(old.counts, function(x) var(x)))
summary(counts.lowvar)
counts.higvar <- names(subset(counts.lowvar,
                              counts.lowvar > quantile(counts.lowvar, .5)))


```

```{r}
old.counts.pc <- norm.inputs.old[[1]] %>%
  as.data.frame() %>%
  select(counts.higvar) 

old.counts.res  <- prcomp(old.counts.pc, scale. = T)$x %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  select(sample, PC1, PC2) %>%
  mutate(datset = "counts")

old.norm.pc <-  norm.result.old %>%
  select(c("sample", counts.higvar)) %>%
  remove_rownames() %>%
  column_to_rownames(var = "sample")
  # select(-Vibrio.phage.ValB1MD.2, -Staphylococcus.virus.Andhra)

old.norm.res  <- prcomp(old.norm.pc, scale. = T)$x%>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  select(sample, PC1, PC2) %>%
  mutate(datset = "normalized")
```

```{r}
# norm.prc <- prcomp(tcga.norm.pc, scale. = T)
# autoplot(norm.prc, loadings = T, loadings.label = T)
# ggsave("../figures/pca_norm-loadings.png", width = 15)
```

## Plot

```{r}

pcs.res <- bind_rows(old.counts.res, old.norm.res) %>%
  left_join(norm.inputs.old[[2]])

pcs.res %>%
  mutate(THCA = ifelse(TCGA.code == "THCA",
                            T, F)) %>%
  ggplot(aes(x = PC1, y = PC2, color = SequencingCenter, fill = SequencingCenter)) +
  facet_wrap(vars(datset), scales = "free") +
  geom_point(alpha = .4) +
  stat_ellipse(geom = "polygon", alpha = .2) +
  scale_fill_viridis_d(aesthetics = c("color", "fill")) +
  theme_bw()
ggsave("../figures/pca_compare-FFPE_expr_old.png")
```

## New normalization formula
```{r}
new.counts <- norm.inputs.new[[1]] %>%
  as.data.frame()
counts.lowvar <- unlist(lapply(new.counts, function(x) var(x)))
summary(counts.lowvar)
counts.higvar <- names(subset(counts.lowvar,
                              counts.lowvar > quantile(counts.lowvar, .5)))


```

```{r}
new.counts.pc <- norm.inputs.new[[1]] %>%
  as.data.frame() %>%
  select(counts.higvar) 

new.counts.res  <- prcomp(new.counts.pc, scale. = T)$x %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  select(sample, PC1, PC2) %>%
  mutate(datset = "counts")

new.norm.pc <-  norm.result.new %>%
  select(c("sample", counts.higvar)) %>%
  remove_rownames() %>%
  column_to_rownames(var = "sample")
  # select(-Vibrio.phage.ValB1MD.2, -Staphylococcus.virus.Andhra)

new.norm.res  <- prcomp(new.norm.pc, scale. = T)$x%>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  select(sample, PC1, PC2) %>%
  mutate(datset = "normalized")
```

```{r}
# norm.prc <- prcomp(tcga.norm.pc, scale. = T)
# autoplot(norm.prc, loadings = T, loadings.label = T)
# ggsave("../figures/pca_norm-loadings.png", width = 15)
```

## Plot

```{r}

new.pcs.res <- bind_rows(new.counts.res, new.norm.res) %>%
  left_join(norm.inputs.new[[2]])

new.pcs.res %>%
  ggplot(aes(x = PC1, y = PC2, color = SequencingCenter, fill = SequencingCenter)) +
  facet_wrap(vars(datset), scales = "free") +
  geom_point(alpha = .4) +
  stat_ellipse(geom = "polygon", alpha = .2) +
  scale_fill_viridis_d(aesthetics = c("color", "fill")) +
  theme_bw()
ggsave("../figures/pca_compare-FFPE_expr_new.png")
```

# What are those groups?

```{r}
pcs.grouplab <- new.pcs.res %>%
  filter(datset == "normalized") %>%
  mutate(pc.group = ifelse(PC1 < -300, "ClusterA","main.group"))

pcs.grouplab %>% 
  group_by(pc.group, tissue_source_site) %>%
  tally()
```

```{r}
pcs.res %>%
  ggplot(aes(x = PC1, y = PC2, color = tissue_source_site, fill = tissue_source_site)) +
  facet_wrap(vars(datset), scales = "free") +
  geom_point(alpha = .4, show.legend = F) +
  stat_ellipse(geom = "polygon", alpha = .2, show.legend = F) +
  scale_fill_viridis_d(aesthetics = c("color", "fill")) +
  theme_bw()
```

# Volcano

```{r}

```


