---
title: "Visualize correlations"
author: "Rebecca Hoyd"
date: "3/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(viridis)
```

# Load data

```{r}
tcc.all <- read.csv("../data/correlations_mic-clin_TCC.csv",
                    stringsAsFactors = F)
tcc.split <- read.csv("../data/correlations_mic-clin_TCC_split-cancer.csv",
                      stringsAsFactors = F)
tcga.all <- read.csv("../data/correlations_mic-clin_TCGA.csv",
                     stringsAsFactors = F)
tcga.split <- read.csv("../data/correlations_mic-clin_TCGA_split-cancer.csv",
                       stringsAsFactors = F)
```

# Format

```{r}
tcc.res <- tcc.all %>%
  mutate(cancer = "All") %>%
  bind_rows(tcc.split)

tcga.res <- tcga.all %>%
  mutate(cancer = "All") %>%
  bind_rows(tcga.split)

corr.res <- bind_rows(tcc.res, tcga.res)
```

```{r}
matched.cancers <- unique(subset(corr.res, corr.res$datset == "TCGA")$cancer)
corr.res.red <- corr.res %>%
  filter(cancer %in% matched.cancers) %>%
  group_by(microbe) %>%
  mutate(choosemic = any(p.value < 0.05)) %>%
  ungroup() %>%
  filter(choosemic == T) %>%
  mutate(datset = ifelse(datset == "TCGA", "TCGA", "ORIEN"))
```

# Plots 

```{r}
plotScoreCorr <- function(sname){
  p <- corr.res.red %>%
    filter(score == sname) %>%
    mutate(TaxLev = str_sub(microbe, 1, 1)) %>%
    ggplot(aes(x = microbe, y = cancer, fill = estimate)) +
    facet_wrap(TaxLev ~ datset, scales = "free", ncol = 2) +
    geom_tile() +
    labs(x = "", y = "") +
    scale_fill_viridis_c(option = "mako", name = "Correlation with Age") +
    theme_classic() +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank())
  
  return(p)
}
```

```{r}
scores <- unique(corr.res.red$score)
scoreplots <- lapply(scores, function(x) plotScoreCorr(x))
names(scoreplots) <- scores
```

```{r}
lapply(scores, function(x) ggsave(scoreplots[[x]],
                                  filename = paste0("../figures/heatmap_corr_", 
                                                    x, ".png"),
                                  device = "png",
                                  height = 14))
```

