---
title: "visualize survival results"
author: "Rebecca Hoyd"
date: "2/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggforce)
library(devEMF)
```

# Load

```{r}
tcc.all <- readRDS("../data/survival_tcc_all-cancers.RDS") %>%
  bind_rows()
tcga.all <- readRDS("../data/survival_tcga_all-cancers.RDS") %>%
  bind_rows()
tcc.split <- readRDS("../data/survival_tcc_split-cancers.RDS")
tcga.split <- readRDS("../data/survival_tcga_split-cancers.RDS")
```

```{r}
tcc.all.join <- tcc.all %>%
  mutate(cancer = "All")
tcga.all.join <- tcga.all %>%
  mutate(cancer = "All")

surv.res <- bind_rows(tcc.all.join, tcga.all.join, tcc.split, tcga.split)
```
# Forrest

## Format

```{r}
formForForest <- function(cname, resdf){
  tmp <- resdf %>%
    filter(cancer == cname) %>%
    group_by(microbe) %>%
    mutate(choosemic = any(p.value < 0.05)) %>%
    ungroup() %>%
    filter(choosemic == TRUE)
  
  micord <- tmp %>%
    filter(datset == "TCC") %>%
    arrange(hazard.ratio)
  micord <- micord$microbe
  
  tmp2 <- tmp %>%
    mutate(confint.high = ifelse(confint.high == Inf, NA, confint.high),
           confint.low = ifelse(confint.low == 0, NA, confint.low),
           microbe = fct_relevel(microbe, micord)) 
}

plotForest <- function(df){
  p <- df %>%
    ggplot(aes(x = microbe, y = log(hazard.ratio) 
               # ymin = confint.low, ymax = confint.high
    )) +
    facet_wrap(vars(datset), ncol = 1) +
    geom_point() +
    geom_hline(yintercept = 0, lty = 2) +
    labs(x = "", y = "") +
    theme_bw() +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank())
  
  return(p)
}
```

```{r}
matched.cancers <- unique(subset(surv.res, surv.res$datset == "TCGA")$cancer)
plotdat.ls <- lapply(matched.cancers, function(x) formForForest(x, surv.res))
names(plotdat.ls) <- matched.cancers
```

## Plot

```{r}
fplots.ls <- lapply(plotdat.ls, function(x) plotForest(x))

fplots.ls
```

```{r}
lapply(matched.cancers, function(x) ggsave(plot = fplots.ls[[x]],
                                           filename = paste0("../figures/forest_", 
                                                             x, ".png"), 
                                           device = "png"))
```

# Circos

## Formatting

```{r make big plot input object}
tile.input <- surv.res %>%
  mutate(taxalev = str_sub(microbe,1,1),
         sigcode = p.value < 0.05) %>%
  select(microbe, taxalev, sigcode, datset, cancer)


```

```{r find the variables that we want to limit the plots on}
test <- tile.input %>%
  filter(sigcode == T & !grepl("Other", cancer)) %>%
  group_by(cancer) %>%
  tally()

good.cancers <- test$cancer
all.taxlevs <- unique(tile.input$taxalev)
```

## geom_tile

```{r ensure consistent fill scale}
vir.cols <- viridis::viridis_pal()(9)
names(vir.cols) <- good.cancers
```

```{r plotting function}
polarizedHeatmaps <- function(tlev, dset, yadj){
  tile.input %>%
    filter(datset == dset & taxalev == tlev) %>%
    filter(cancer %in% good.cancers) %>%
    mutate(cancer.code = ifelse(sigcode == T, cancer, NA),
           cancer = as.numeric(as.factor(cancer)) + yadj) %>%
    ggplot(aes(x = microbe, y = cancer, fill = cancer.code)) +
    geom_tile() +
    ylim(c(0,100)) +
    scale_fill_manual(values = vir.cols, name = "", na.value = "grey95") + 
    theme_void() +
    theme(axis.text.x = element_blank(),
          axis.ticks = element_blank()) +
    coord_polar()
}
```

```{r}
ringplot.tcc.ls <- list(d = polarizedHeatmaps("d", "TCC", 1),
                        k = polarizedHeatmaps("k", "TCC", 12),
                        p = polarizedHeatmaps("p", "TCC", 23),
                        c = polarizedHeatmaps("c", "TCC", 34),
                        o = polarizedHeatmaps("o", "TCC", 45),
                        f = polarizedHeatmaps("f", "TCC", 56),
                        g = polarizedHeatmaps("g", "TCC", 67),
                        s = polarizedHeatmaps("s", "TCC", 78))

ringplot.tcc.ls
```

```{r}
lapply(as.character(all.taxlevs), function(x) ggsave(plot = ringplot.tcc.ls[[x]],
                                                     filename = 
                                                       paste0("../figures/",
                                                              "heatmap_ring_TCC_",
                                                              x, ".pdf"),
                                                     dev = "pdf"))
```

```{r}
ringplot.tcga.ls <- list(d = polarizedHeatmaps("d", "TCGA", 1),
                        k = polarizedHeatmaps("k", "TCGA", 12),
                        p = polarizedHeatmaps("p", "TCGA", 23),
                        c = polarizedHeatmaps("c", "TCGA", 34),
                        o = polarizedHeatmaps("o", "TCGA", 45),
                        f = polarizedHeatmaps("f", "TCGA", 56),
                        g = polarizedHeatmaps("g", "TCGA", 67),
                        s = polarizedHeatmaps("s", "TCGA", 78))

ringplot.tcga.ls
```

```{r}
lapply(as.character(all.taxlevs), function(x) ggsave(plot = ringplot.tcga.ls[[x]],
                                                     filename = 
                                                       paste0("../figures/",
                                                              "heatmap_ring_TCGA_",
                                                              x, ".pdf"),
                                                     dev = "pdf"))
```

## repeat for agreement plot

```{r}
agree.input <- surv.res %>%
  filter(cancer %in% good.cancers) %>%
  mutate(hazard.dir = ifelse(hazard.ratio > 1, "neg", "pos"),
         signif = p.value < 0.05,
         dirsig = paste(hazard.dir, signif)) %>%
  select(microbe, dirsig, cancer, datset) %>%
  spread(key = "datset", value = "dirsig") %>%
  separate(TCC, into = c("TCC.dir", "TCC.sig")) %>%
  separate(TCGA, into = c("TCGA.dir", "TCGA.sig")) %>%
  mutate(agree.code = TCC.sig == T & TCGA.sig == T & TCC.dir == TCGA.dir) %>%
  mutate(taxalev = str_sub(microbe,1,1))
```

```{r}
agreeingHeatmaps <- function(tlev, yadj){
    agree.input %>%
    filter(taxalev == tlev) %>%
    filter(cancer %in% good.cancers) %>%
    mutate(cancer.code = ifelse(agree.code == T, cancer, NA),
           cancer = as.numeric(as.factor(cancer)) + yadj) %>%
    ggplot(aes(x = microbe, y = cancer, fill = cancer.code)) +
    geom_tile() +
    ylim(c(0,100)) +
    scale_fill_manual(values = vir.cols, name = "", na.value = "grey95") +
    theme_void() +
    theme(axis.text.x = element_blank(),
          axis.ticks = element_blank()) +
    coord_polar()
}
```

```{r}
ringplot.agree.ls <- list(d = agreeingHeatmaps("d", 1),
                          k = agreeingHeatmaps("k", 12),
                          p = agreeingHeatmaps("p", 23),
                          c = agreeingHeatmaps("c", 34),
                          o = agreeingHeatmaps("o", 45),
                          f = agreeingHeatmaps("f", 56),
                          g = agreeingHeatmaps("g", 67),
                          s = agreeingHeatmaps("s", 78))

ringplot.agree.ls
```

```{r}
lapply(as.character(all.taxlevs), function(x) ggsave(plot = ringplot.agree.ls[[x]],
                                                     filename = 
                                                       paste0("../figures/",
                                                              "heatmap_ring_agree_",
                                                              x, ".pdf"),
                                                     dev = "pdf"))
```

# Example curves

```{r}
poss.choices <- agree.input %>%
  filter(agree.code == T) %>%
  select(microbe, cancer) %>%
  left_join(surv.res) %>%
  filter(prevalence.1 > 10) %>%
  add_count(microbe, cancer) %>%
  filter(n>1)

```

```{r as forest plot}
poss.choices %>%
  ggplot(aes(x = hazard.ratio, y = datset)) +
  facet_wrap(vars(microbe), ncol = 1, scales = "free_x") +
  geom_point() +
  geom_segment(inherit.aes = F, aes(x = confint.low, xend = confint.high,
                                    y = datset, yend = datset)) +
  geom_vline(xintercept = 1, lty = 2) +
  labs(x = "", y = "") +
  theme_bw()

ggsave("../figures/forest_example-microbes.pdf")
```
