---
title: "Visualize correlations"
author: "Rebecca Hoyd"
date: "3/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(viridis)
```

# Load data

```{r}
tcc.all <- read.csv("../data/correlations_mic-clin_TCC.csv",
                    stringsAsFactors = F)
tcc.split <- read.csv("../data/correlations_mic-clin_TCC_split-cancer.csv",
                      stringsAsFactors = F)
tcga.all <- read.csv("../data/correlations_mic-clin_TCGA.csv",
                     stringsAsFactors = F)
tcga.split <- read.csv("../data/correlations_mic-clin_TCGA_split-cancer.csv",
                       stringsAsFactors = F)
```

# Format

```{r}
tcc.res <- tcc.all %>%
  mutate(cancer = "All") %>%
  bind_rows(tcc.split)

tcga.res <- tcga.all %>%
  mutate(cancer = "All") %>%
  bind_rows(tcga.split)

corr.res <- bind_rows(tcc.res, tcga.res)
```

```{r}
matched.cancers <- unique(subset(corr.res, corr.res$datset == "TCGA")$cancer)
corr.res.red <- corr.res %>%
  filter(cancer %in% matched.cancers) %>%
  group_by(microbe) %>%
  mutate(choosemic = any(p.value < 0.05)) %>%
  ungroup() %>%
  filter(choosemic == T) %>%
  mutate(datset = ifelse(datset == "TCGA", "TCGA", "ORIEN"))
```

# Plots 

```{r}
plotScoreCorr <- function(sname){
  p <- corr.res.red %>%
    mutate(TaxLev = str_sub(microbe, 1, 1)) %>%
    filter(score == sname & TaxLev == "g") %>%
    ggplot(aes(x = microbe, y = cancer, fill = estimate)) +
    facet_wrap(vars(datset), scales = "free", ncol = 2) +
    geom_tile() +
    labs(x = "", y = "") +
    scale_fill_viridis_c(option = "mako", name = "Correlation Estimate") +
    theme_classic() +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank())
  
  return(p)
}
```

```{r}
scores <- unique(corr.res.red$score)
scoreplots <- lapply(scores, function(x) plotScoreCorr(x))
names(scoreplots) <- scores
```

```{r}
lapply(scores, function(x) ggsave(scoreplots[[x]],
                                  filename = paste0("../figures/heatmap_corr_", 
                                                    x, ".pdf"),
                                  device = "pdf"))
```


# Lollipop version

## Choose microbes

```{r}
tcc.newlab <- tcc.res %>%
  filter(p.value < 0.05) %>%
  mutate(TCC.est = estimate, 
         dir = TCC.est >= 0) %>%
  select(TCC.est, dir, microbe, score, cancer)

tcga.newlab <- tcga.res %>%
  filter(p.value < 0.05) %>%
  mutate(TCGA.est = estimate, 
         dir = TCGA.est >= 0) %>%
  select(TCGA.est, dir, microbe, score, cancer)

corrs.matched.1 <- inner_join(tcc.newlab, tcga.newlab)

corrs.matched <- tcc.newlab %>%
  filter(cancer %in% c("LUAD", "LUSC", "SARC", "KIRC", "BLCA") & score == "bmi") %>%
  bind_rows(corrs.matched.1)

corrs.matched %>%
  group_by(cancer, score) %>%
  tally()
```

## Plot

```{r}
# plotScoreLolli <- function(sname){
#   tmp <- corrs.matched %>%
#     filter(score == sname) %>%
#     pivot_longer(cols = c(TCC.est, TCGA.est),
#                  names_to = "datset", values_to = "estimate")
#   
#   tmp %>%
#     ggplot(aes(x = microbe,y = estimate,
#                xend = microbe, yend = 0)) +
#   facet_wrap(vars(cancer), ncol = 1) +
#     geom_segment() +
#     geom_point(aes(color = datset)) +
#     geom_hline(yintercept = 0, lty = 2) +
#     labs(x = "", y = "") +
#     scale_color_manual(breaks = c("TCC.est", "TCGA.est"),
#                        labels = c("ORIEN", "TCGA"),
#                        values = c("red", "blue"),
#                        name = "") +
#     theme_classic() +
#     theme(axis.text.x = element_blank(),
#           axis.ticks.x = element_blank())
# }
```

```{r}
# plotScoreLolli("age")
# ggsave("../figures/lollipop_mic-clin_age.pdf")
# 
# plotScoreLolli("buffa.score")
# ggsave("../figures/lollipop_mic-clin_buffa.pdf")
# 
# plotScoreLolli("MitoScore")
# ggsave("../figures/lollipop_mic-clin_mito.pdf")
```

```{r}
matched.long <- corrs.matched %>%
  pivot_longer(cols = c(TCC.est, TCGA.est),
               names_to = "datset", values_to = "estimate") %>%
  filter(score != "MitoScore") %>%
  mutate(score = case_when(score == "bmi" ~ "BMI",
                           score == "age" ~ "Age",
                           score == "buffa.score" ~ "Buffa"))

matched.long %>%
  ggplot(aes(y = microbe,x = estimate,
             yend = microbe, xend = 0)) +
  facet_grid(cancer ~ score) +
  geom_segment() +
  geom_point(aes(color = datset)) +
  geom_vline(xintercept = 0, lty = 2) +
  labs(x = "Correlation estimate", y = "") +
  scale_color_manual(breaks = c("TCC.est", "TCGA.est"),
                     labels = c("ORIEN", "TCGA"),
                     values = c("red", "blue"),
                     name = "",
                     ) +
  theme_classic() +
  theme(text = element_text(size = 10),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "top")
ggsave("../figures/lollipop_mic-clin.pdf", height = 6, width = 4)
```
