---
title: "figures_correlations"
author: "Rebecca Hoyd"
date: "February 6, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(tidyr)
library(broom)
library(survival)
library(survminer)
library(forcats)
library(Hmisc)
library(devEMF)
library(ggforce)
library(readxl)
```

# Load data
```{r}
exo.ra <- read.csv("../../data/agg_exo-ra_taxonomy.csv", stringsAsFactors = F)
clindat <- read_excel("C:/Users/Leste/Desktop/summer intern 2020/GI Patient list -detailed - PM edit.xlsx") %>%
  rename("Treatment" = '"Treatment"')
kingphyl <- read.csv("../../data/fix-king-assign_manual-edits.csv", stringsAsFactors = F)
```


# Format for survival calculations

```{r fix odd taxa assignments}
# phyl.assign <- unique(exo.ra[, c("phylum", "kingdom")])
# write.csv(phyl.assign, "../../data/fix-king-assign.csv", row.names = F)


exo.taxfix.domain <- exo.ra %>%
  filter(is.na(taxonomy)) %>%
  mutate(domain = ifelse(grepl("phage|virus", spec.join, ignore.case = TRUE), "Viruses", domain),
         domain = ifelse(grepl("calothrix", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("anabaena", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("chondrocystis", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("cyanobacterium", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("dolichospermum", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("euhalothece", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("fischerella", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("geitlerinema", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("geminocystis", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("gloeobacter", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("gloeothece", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("limnospira", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("microcoleus", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("moorea", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("nostoc", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("oscillatoria", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("prochlorococcus", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("rivularia", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("synechococcus", spec.join, ignore.case = TRUE) & !grepl("phage|virus", spec.join,
                                                                                        ignore.case = TRUE),
                         "Bacteria", domain),
         domain = ifelse(grepl("tenericutes", spec.join, ignore.case = TRUE), "Bacteria", domain),
         domain = ifelse(grepl("trichodesmium", spec.join, ignore.case = TRUE), "Bacteria", domain)
         )

exo.ra <-exo.ra %>%
  filter(!is.na(taxonomy)) %>%
  select(-kingdom) %>%
  left_join(kingphyl)

exo.ra <- bind_rows(exo.ra, exo.taxfix.domain)
```

```{r}
exoRAtowideprev <- function(data, taxlev){
  tmp <- data
  tmp$Taxa <- tmp[[taxlev]]
  tmp.wide<- tmp %>%
    filter(!is.na(Taxa)) %>%
    mutate(Taxa = paste(taxlev, Taxa, sep = "_")) %>%
    group_by(sample, Taxa) %>%
    summarise(ra = sum(ra, na.rm = T)) %>%
    spread(key = "Taxa", value = "ra")
  
  tmp.wide[is.na(tmp.wide)] <- 0
  tmp.prev <- bind_rows(lapply(tmp.wide[,-1], function(x) ifelse(x > 0, 1, 0))) %>%
    mutate(sample = tmp.wide$sample) %>%
    select(sample, everything())
  return(tmp.prev)
}
```

```{r}
taxalevels <- c("domain", "kingdom", "phylum", "class", "order", "family", "genus", "species")

exo.wide.list <- lapply(taxalevels, function(x) exoRAtowideprev(exo.ra, x))
names(exo.wide.list) <- taxalevels

microbes <- unlist(lapply(exo.wide.list, function(x) colnames(x)[-1]))

exo.wide <- bind_cols(exo.wide.list)

clindat <- clindat %>%
  rename("sample" = "RNA SL ID") %>%
  mutate(D.days = `Overall Survival from Dx (days)`,
         C.days = `Days from Collection to Last Follow-Up or Death`,
         vitalstatus = ifelse(`Vital Status` == "Deceased", 1, 0))

loop.input <-clindat %>%
  left_join(exo.wide)

```

# Run surv ~ each microbe, in each treatment, at every taxa level

```{r, error=F, message=F, warning=F}
 treatments <- unique(loop.input$Treatment)
 microbes <- make.names(microbes)
 colnames(loop.input) <- make.names(colnames(loop.input))
 
 treat.res.D <- list()
 treat.res.C <- list()
 mic.res.D <- list()
 mic.res.C <- list()
   for(m in microbes){
     try({
       num <- sum(loop.input[[m]])
       loop.tmp <- loop.input %>%
         filter(vitalstatus == "1")
       n.death <- sum(loop.tmp[[m]])
       mic.res.D[[m]] <- coxph(formula = as.formula(paste0("Surv(D.days, vitalstatus) ~ ", m)), data = loop.input) %>%
         tidy() %>%
         mutate(hazard.ratio.D = exp(estimate),
                pvalue.D = p.value,
                taxa = m,
                n.patient = num,
                n.death = n.death,
                low.bound.D = exp(conf.low),
                upper.bound.D = exp(conf.high)) %>%
         select(hazard.ratio.D, pvalue.D, taxa,n.patient,n.death, low.bound.D, upper.bound.D)
       mic.res.C[[m]] <- coxph(formula = as.formula(paste0("Surv(C.days, vitalstatus) ~ ", m)), data = loop.input) %>%
         tidy() %>%
         mutate(hazard.ratio.C = exp(estimate),
                pvalue.C = p.value,
                taxa = m,
                low.bound.C = exp(conf.low),
                upper.bound.C = exp(conf.high)) %>%
         select(hazard.ratio.C, pvalue.C, taxa,low.bound.C, upper.bound.C)
     })
   treat.res.D[[m]] <- mic.res.D
   mic.res.D <- list()
   treat.res.C[[m]] <- mic.res.C
   mic.res.C <- list()
 }
 
loop.output <- cbind(bind_rows(lapply(treat.res.D, function(x) bind_rows(x))),
                     bind_rows(lapply(treat.res.C, function(x) bind_rows(x))))
loop.output$taxa.1 <- NULL
write.csv(loop.output, "../../data/ASCO_survival-microbe-output.csv", row.names = F)
loop.output <- read.csv("../../data/ASCO_survival-microbe-output.csv", stringsAsFactors = F)
```

# Create heatmap

```{r}
loop.output %>%
  separate(taxa, sep = "_", into = c("Taxa.Level", "Taxa")) %>%
  filter(Taxa.Level != "species") %>%
  ggplot(aes(y = Treatment, x = Taxa, fill = pvalue)) +
  geom_tile() +
  geom_text(aes(label = ifelse(hazard.ratio< 1, "+", "")), size = 1) +
  facet_row(vars(fct_relevel(capitalize(Taxa.Level), capitalize(taxalevels))),
             scales = "free_x", space = "free") +
  labs(x = "", y = "") +
  scale_fill_distiller(guide = "legend", limits = c(0, 1), name = "P.Value",
                       breaks = c(0.000000000001, 0.01, 0.02, 0.03, 0.04, 0.05, 0.1, 0.2, 0.5, 1),
                       values = c(0.000000000001, 0.01, 0.02, 0.03, 0.04, 0.05, 0.1, 0.2, 0.5, 1), 
                       type = "div", palette = "RdBu", direction = 1,
                       labels = c("<0.01", "0.01", "0.02","0.03", "0.04","0.05","0.1", "0.2", "0.5", "1")) +
  theme_classic(base_size = 18) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 3),
        # axis.text.y = element_text(size = 3, vjust = 0.5),
        axis.ticks.y = element_blank()
        # axis.ticks.x = element_blank()
        ) +
  ggsave("../../figures/ASCO/survival-significance.png", width = 35, height = 4)
```

