---
title: "all-taxRank_ras"
author: "Dan Spakowicz"
date: "12/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


```{r read in species names}
exo <- read_csv("../data/aggcounts_all.csv")

exo %>%
  colnames %>%
  head
```

Now need to find the taxonomy information from the kraken or bracken outputs.

```{r taxonomy}
tax <- read.table("../../../ncbi-taxonomy/fullnamelineage.dmp", sep = "\t",
                fill = TRUE,
                stringsAsFactors = FALSE)

tax$V1 <- as.numeric(tax$V1)

head(tax)

files <- list.files(path = "../data/",
                    pattern = "SL\\d*.txt",
                    full.names = TRUE,
                    recursive = TRUE)

ReadAndFilter <- function(file) {
    read.table(file, sep = "\t") %>%
    filter(V4 == "S") %>%
    select(V5)
}

all.ids <- lapply(files, ReadAndFilter)

species.ids <- bind_rows(all.ids) %>%
  unique %>%
  rename("taxid" = "V5")

species.names <- 
  species.ids %>%
  left_join(tax, by = c("taxid" = "V1"))

tax[grep("160808", tax$V1),]





```

This is missing so many ids! Why!?
