---
title: "Make Table 1: Cohort characteristics"
author: "Rebecca Hoyd"
date: "February 6, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tableone)
library(forcats)
library(glue)
library(readxl)
library(flextable)
library(officer)
library(UpSetR)
library(ggdendro)
library(RColorBrewer)

```

# Load data
```{r}
# I'm storing these in my T drive as I suspect the may have identifiable information
clinfiles <- list.files("T:/Labs/Spakowicz/data/exoTCC/", full.names = F, "_Spakowicz")
clinfiles <- paste0("T:/Labs/Spakowicz/data/exoTCC/", clinfiles)

clindat <- lapply(clinfiles, function(x) read_excel(x, na = "N/A"))


```


# Coercing the clinical data into a tidier object
```{r}

for(i in 1:length(clindat)){
  # First, I don't want to have to deal with names poorly formatted for R. 
  colnames(clindat[[i]]) <- make.names(colnames(clindat[[i]]))
}


tho <- clindat[[3]]
```

# General characteristics

```{r}

# Select and adjust dataframe for Table 1
tho.tabnames <- tho %>%
  mutate(Stage  = ifelse(Cancer.Stage.at.Collection %in% c("88", "99", "undeterm.") , 
                         "Unknown", Cancer.Stage.at.Collection),
         BMI = BMI.at.Collection,
         Age = Age.at.Collection,
         Sex = Gender,
         `Vital Status` = Vital.Status,
         Radiation = ifelse(Radiation == "None", 0, 1),
         Surgery = ifelse(grepl("None", Surgery), 0, 1),
         Hormones = ifelse(is.na(Hormone.Therapy), 0, 1),
         IO = ifelse(is.na(I.O.Drug.Name), 0, 1),
         Chemotherapy = ifelse(is.na(Chemo.Drug.Name), 0, 1)
  )
```

```{r}
listVars <- c("BMI", "Age", "Sex", "Cancer", "Stage", "Vital Status")
catVars <- c("Sex", "Cancer", "Stage", "Vital Status")
```

```{r table 1}
table1 <- CreateTableOne(vars = listVars,
                         data = tho.tabnames,
                         factorVars = catVars)
table1
```

# Treatment types prescribed each patient

```{r}
upsetdat <- tho.tabnames %>%
  select(Radiation, Hormones, Surgery, Chemotherapy, IO) %>%
  as.data.frame()

upset(upsetdat)
```

# Drugs given

## Chemotherapy
```{r learn about condensing variables}

tho %>% 
  mutate(Chemo.Drug.Name = tolower(Chemo.Drug.Name)) %>%
  # separate(Chemo.Drug.Name, into = c('testChem')) %>%
  group_by(Chemo.Drug.Name) %>%
  tally() %>%
  arrange(desc(n)) %>%
  mutate(`%.given` = n/nrow(tho)) %>%
  print()
```


## IO

```{r}

tho %>%
  mutate(I.O.Drug.Name = tolower(I.O.Drug.Name)) %>%
  # separate(I.O.Drug.Name, into = c('testIO')) %>%
  group_by(I.O.Drug.Name) %>%
  tally() %>%
  arrange(desc(n)) %>%
  mutate(`%.given` = n/nrow(tho))
```


# Time from diagnosis/treatment to when the samples were taken

## Days after diagnosis


```{r}
tho %>%
  mutate(days.from.diagnosis.to.collection = Overall.Survival.from.Dx..days. - Days.from.Collection.to.Last.Follow.Up.or.Death) %>%
  ggplot(aes(x = days.from.diagnosis.to.collection)) +
  geom_histogram() +
  theme_bw() +
  labs(x = "Days", y = "", title = "Time from diagnosis to sample collection")
```

## Days after treatment - Chemo

```{r}
tho %>%
  mutate(days.from.chemo.to.collection = Days.from.Chemo.Start.to.Last.Follow.Up.or.Death -
           Days.from.Collection.to.Last.Follow.Up.or.Death) %>%
  ggplot(aes(x = days.from.chemo.to.collection)) +
  geom_histogram() +
  theme_bw() +
  labs(x = "Days", y = "", title = "Time from chemotherapy to sample collection")
```

## Days after treatment - IO

```{r}
tho %>%
  mutate(days.from.io.to.collection = Days.from.I.O.Start.to.Last.Follow.Up.or.Death -
           Days.from.Collection.to.Last.Follow.Up.or.Death) %>%
  ggplot(aes(x = days.from.io.to.collection)) +
  geom_histogram() +
  theme_bw() +
  labs(x = "Days", y = "", title = "Time from immunotherapy to sample collection")
```

# Timeline of events

```{r calculate dates in terms of diagnosis}
tho.times <- tho %>%
  mutate(Stage  = ifelse(Cancer.Stage.at.Collection %in% c("88", "99", "undeterm.") , 
                         "Unknown", Cancer.Stage.at.Collection)) %>%
  select(contains("Days"), Stage)
colnames(tho.times) <- c("Death.or.last.followup", "Chemo.Start", "IO.Start", "Radiation.start", 
                         "Hormones.start", "Sample.Collection", "Stage")

tho.times <- tho.times %>%
  mutate(pat.id = paste0(id(tho.times), "a")) %>%
  gather(-Death.or.last.followup, -pat.id, -Stage, key = "Event.type", value = "days.ev.to.ev") %>%
  mutate(days.diag.to.ev = Death.or.last.followup - days.ev.to.ev) %>%
  select(-days.ev.to.ev) %>%
  spread(key = "Event.type", value = "days.diag.to.ev") %>%
  mutate(Diagnosis = 0) %>%
  gather(-pat.id, -Stage, key = "Event.type", value = "days.diag.to.ev")
```

```{r cluster patients}
# tho.time.mat <- tho.times %>%
#   spread(key = "Event.type", value = "days.diag.to.ev") %>%
#   column_to_rownames(var = "pat.id") %>%
#   select(-Stage)
# 
# pat.ord <- tho.time.mat %>%
#   dist() %>%
#   hclust() %>%
#   dendro_data()
# pat.ord <- pat.ord$labels %>%
#   arrange(x)
# pat.ord <- as.character(pat.ord$label)

tho.ev.ord <- tho.times %>%
  arrange(pat.id, days.diag.to.ev) %>%
  group_by(pat.id) %>%
  filter(!is.na(days.diag.to.ev) & Event.type != "Diagnosis") %>%
  mutate(Event.type = gsub("\\.", " ", Event.type)) %>%
  summarise(evord = paste(Event.type, collapse = ", ")) %>%
  arrange(evord)
         

```


```{r make timeline figure, fig.height = 8, fig.width = 7}
getpallete <- colorRampPalette(brewer.pal(9, "PRGn"))

tho.times %>%
  filter(days.diag.to.ev >= 0) %>% #This line removes a single patient listed as having chemo >2000 days before                                            diagnosis and one who started radiation 3 days before diagnosis.
  ggplot(aes(x = days.diag.to.ev, y = fct_relevel(pat.id, tho.ev.ord$pat.id))) +
  geom_path(alpha = .75, aes(color = Stage)) +
  geom_point(aes(shape = fct_relevel(Event.type, "Diagnosis", after = 6))) +
  scale_color_manual(breaks = sort(unique(tho.times$Stage)), values = c(getpallete(10), "grey")) +
  labs(x = "Days from diagnosis to event", y = "Patient") +
  theme_classic() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  ggsave("../figures/timeline-of-events_THO.png", height = 8, width = 7)
```