---
title: "all-taxRank_ras"
author: "Dan Spakowicz"
date: "12/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(stringr)
```


# Load data
```{r read in species names}
exo.gi <- read.csv("../data/exo-ra_gi_filtered-with-tcga.csv", stringsAsFactors = F)[,-1]
met.all <- read.table("../data/kraken2-metaphlan-taxonomy.txt", sep = "\t", stringsAsFactors = F) %>%
  rename("Taxonomy" = "V1")

```
# Create key

```{r}
# Somthing's wrong with met.dall -it seems like certain rows are getting pasted together?

met.good <- met.all %>%
  filter(!grepl("\n", Taxonomy))
met.fix <- met.all %>%
  filter(grepl("\n", Taxonomy)) 

fix.taxa.amalgam <- paste(met.fix$Taxonomy, collapse = "\n")
fix.taxa.split <- str_split(pattern = "\n", fix.taxa.amalgam)[[1]]
met.repared <- as.data.frame(cbind(Taxonomy = fix.taxa.split,
                                   V2 = NA))%>%
  separate(Taxonomy, into = c("Taxonomy"), sep = "\t")

met.all2 <- bind_rows(met.good, met.repared)

taxkey <- met.all2 %>%
  filter(grepl("s__", Taxonomy)) %>%
  mutate(specjoin = gsub(".*s__(.*)", "\\1", Taxonomy)) %>%
  separate(specjoin, into = c("Genera", "Species"), sep = " ") %>%
  mutate(specjoin = paste0(Genera, ".", Species),
         specjoin = ifelse(grepl("-", specjoin), gsub("(.*\\..*)\\..*", "\\1", gsub("-", ".", specjoin)), specjoin))
```

```{r}
exo.gi.forjoin <- exo.gi %>%
  gather(-sample, key = "microbe", value = "exo.ra") %>%
  separate(microbe, into = c("Genera.gi", "Species.gi"), sep = "\\.", remove = F) %>%
  mutate(specjoin = paste0(Genera.gi, ".", Species.gi),
         specjoin = ifelse(grepl("sp$", specjoin), gsub("sp$", "sp.", specjoin), specjoin),
         specjoin = ifelse(grepl("^X\\.", specjoin), 
                           paste0(gsub("X\\.", "[", specjoin), "].", gsub(".*\\.(.*)", "\\1", microbe)),
                           specjoin))
```

# Join, split taxonomy

```{r}
exo.gi.testtax <- exo.gi.forjoin %>%
  left_join(taxkey)

# testtax <- unique(exo.gi.testtax[, c("microbe", "specjoin", "Taxonomy")])
# finderr <- testtax %>% filter(is.na(Taxonomy))
# exo.gi.subset <- exo.gi.testtax[1:1000,]


exo.gi.tax <- exo.gi.testtax %>%
  mutate(domain = gsub("(d__\\w+).*", "\\1", Taxonomy),
         kingdom = ifelse(grepl("k__", Taxonomy),gsub(".*(k__\\w+).*", "\\1", Taxonomy), NA),
         phylum = ifelse(grepl("p__", Taxonomy),gsub(".*(p__\\w+).*", "\\1", Taxonomy), NA),
         order = ifelse(grepl("o__", Taxonomy),gsub(".*(o__\\w+).*", "\\1", Taxonomy), NA),
         class = ifelse(grepl("c__", Taxonomy),gsub(".*(c__\\w+).*", "\\1", Taxonomy), NA),
         family = ifelse(grepl("f__", Taxonomy),gsub(".*(f__\\w+).*", "\\1", Taxonomy), NA),
         genus = ifelse(grepl("g__", Taxonomy),gsub(".*(g__\\w+).*", "\\1", Taxonomy), NA),
         species = gsub(".*(s__.*)", "\\1", Taxonomy)
  ) %>%
  dplyr::select(sample, microbe, Taxonomy, domain, kingdom, phylum, class, order, family, genus, species, exo.ra)

```

# Save

```{r}
write.csv(exo.gi.tax, "../data/exo-ra_gi_tcga-filtered_taxonomy.csv", row.names = F)
```

