---
title: "check percent unassigned reads"
author: "Rebecca Hoyd"
date: "7/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(broom)
```

# Testing with GI

Playing around to find how to extract the data, making function

```{r}
# gi.files <- list.files("/fs/ess/PAS1695/generate-inputs/ORIEN-processing/data/kreports/GI-ColorectalCancer",
#                        full.names = T)
# gi.krep <- subset(gi.files, !grepl("bracken", gi.files) & !grepl("core", gi.files))
# 
# test.krep <- lapply(gi.krep, function(x) try(read.table(x, sep = "\t", header = F, stringsAsFactors = F)))
# perc.unc <- test.krep$V1[1]
```

```{r}
pull_unclassified_percent <- function(krep.dir, sum.name){
  dir.files <- list.files(krep.dir, full.names = T)
  dir.krep <- subset(dir.files, !grepl("bracken", dir.files) & !grepl("core", dir.files))
  
  krep.ls <- lapply(dir.krep, function(x) try(read.table(x, sep = "\t", header = F, nrows = 5)))
  unc.perc <- unlist(lapply(krep.ls, function(x) try(x$V1[1])))
  unc.perc.clean <- as.numeric(subset(unc.perc, !grepl("Error", unc.perc)))
  unc.sum <- summary(unc.perc.clean) %>%
    tidy() %>%
    mutate(Name = sum.name)
  return(unc.sum)
}
```

# Apply to all TCC cancers

```{r}
tcc.cancers <- list.files("/fs/ess/PAS1695/generate-inputs/ORIEN-processing/data/kreports")
tcc.dirs <- paste0("/fs/ess/PAS1695/generate-inputs/ORIEN-processing/data/kreports/", tcc.cancers)
names(tcc.dirs) <- tcc.cancers

summarize.percent.UC <- lapply(tcc.cancers, function(x) pull_unclassified_percent(tcc.dirs[x], x)) %>%
  bind_rows()
```

```{r}
summarize.percent.UC

write.csv(summarize.percent.UC, "../data/check-kraken2-unclassified.csv", row.names = F)
```


