---
title: "exploratory_survival"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(survminer)
library(survival)
library(ggplot2)
library(tidyr)
library(broom)
```

# Load data
```{r}
tcc.exora <- readRDS("/fs/ess/PAS1695/projects/exotic/data/devout/tcc.exora.taxonomy.RDS")
tcga.exora <- readRDS("/fs/ess/PAS1695/projects/exotic/data/devout/tcga.exora.taxonomy.RDS")

tcga.clinical <- readRDS("/fs/ess/PAS1695/projects/exotic/data/drake-output/2021-03-25/tcga.clin.tum.RDS")
```

# Format
```{r}
tcga.ra.g <- tcga.exora %>%
  group_by(sample, genus) %>%
  summarise(ra = sum(exo.ra)) %>%
  group_by(genus) %>%
  mutate(cutoff = median(ra)) %>%
  ungroup() %>%
  mutate(gen.highexp =ifelse(ra >cutoff, 1, 0)) %>%
  select(sample, genus, gen.highexp) %>%
  spread(key = genus, value = gen.highexp)

tcga.survin <- tcga.clinical %>%
  mutate(days = coalesce(days_to_death, days_to_last_follow_up),
         vitalstatus = ifelse(vital_status == "Dead", 1, 0),
         sample = file_id.BAM) %>%
  select(sample, days, vitalstatus, cancer) %>%
  inner_join(tcga.ra.g)


```

# Run survival analysis

```{r}
cancers <- unique(tcga.survin$cancer)
microbes <- colnames(tcga.ra.g[,-1])

tcga.survres <- list()

for(canc in cancers){
  survtmp <- tcga.survin %>%
    filter(cancer == canc)
  
  tcga.survres[[canc]] <- lapply(microbes, function(x) coxph(as.formula(paste0("Surv(days, vitalstatus) ~ `",
                                                                               x, "`")), 
                                                             data = survtmp) %>%
                                   tidy() %>%
                                   mutate(genus = x,
                                          cancer = canc)) %>%
    bind_rows()
}
```

# Plot

```{r}
tcga.survres.df <- bind_rows(tcga.survres)

tcga.survres.df %>%
  arrange(p.value) %>%
  head()
```

```{r}
tcga.survres.df %>%
  mutate(p.sig = ifelse(p.value < 0.05, "significant", "not significant")) %>%
  ggplot(aes(x = genus, y = cancer, fill = p.sig)) +
  geom_tile() +
  scale_fill_manual(breaks = c("not significant", "significant"),
                    values = c("grey70", "black"),
                    name = "Significance") +
  labs(x = "", y = "") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```